# Generated by Django 4.1.3 on 2022-12-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Image',
            new_name='image',
        ),
    ]
